### ISSUE TITLE
Suggestion: Provide concrete solutions for common issues

### ISSUE THREAD

**Issue by chiayewken** [acl-org/aclpubcheck#15]
Thank you for the script to help check the formatting automatically. However, I think the process can be sped up for everyone, if you can provide concrete examples and fixes for common formatting errors. Some of the common issues may be:

1. Text exceeds margin
2. Image exceeds margin
3. Wrong fonts
4. Wrong template

Currently, the suggestions in aclpubcheck_additional_info.pdf are vague ("similar bit of latex"), or do not cover general cases (what if the main text bleeds into margin?).

**Comment by ryancotterell** [comment]
Thanks for your comment. It's very hard to prescribe a general recipe to fix the margin issues -- they are generally caused by equations bleeding over or figures bleeding over. You can the adjustbox package [https://ctan.org/pkg/adjustbox?lang=en].

The wrong font error is harder to diagnose because it only comes up if you manually changed the font. The same with the template -- if you use the right sty file, you'll have the right font and temoplate.

**Comment by crux82** [comment]
Yes, I totally agree with Ryan. 

aclpubcheck does its best to suggest where the problem is. Most of the errors (i.e., problems related of text/images out of the margin) are related to the input text in latex.
