### ISSUE TITLE
Format check does not work for ethical statement section

### ISSUE THREAD

**Issue by Faldict** [acl-org/aclpubcheck#2]
Hi,

While using the program for checking the format of my ACL camera-ready, I find out that the program doesn't work for the ethical statement section. Specifically, i have a ethical statement section at page 9. However, after running the program

```
python3 aclpubcheck/formatchecker.py --paper_type long MY_PAPER
```

There is one error:

> Error (Page Limit): Paper exceeds the page limit because first (References, Acknowledgments, Ethics Statement) was found on page 10, line 40.

This is because the formatchecker failed to detect the ethical statement section. I explored a little bit more. The retrieved text at page 9 was

> EthicalConsiderations

There is no spaces in the retrieved text. And the code, in https://github.com/acl-org/aclpubcheck/blob/main/aclpubcheck/formatchecker.py#L210-L224, actually assumes there is any space between words.

**Comment by ryancotterell** [comment]
Thanks for spotting this! Can you email me your paper at ryan.cotterell@gmail.com? We'll put in a work-around.

**Comment by prakharguptaz** [comment]
Hi @ryancotterell , I also encountered the same error with my paper (sent to you via email). I think the issue is same - I have a "Ethical Considerations & Broader Impact" section on page 10. But the text extracted is EthicalConsiderations&BroaderImpact. If I add    EthicalConsiderations in the candidates set https://github.com/acl-org/aclpubcheck/blob/0e1ac0050dadd6d06c09a866b0fd8c8f3f5b177a/aclpubcheck/formatchecker.py#L210-L224 the error disappears.
