### ISSUE TITLE
Getting "ImportError: MagickWand shared library not found." even though Wand is installed.

### ISSUE THREAD

**Issue by jakpra** [acl-org/aclpubcheck#50]
```
~/aclpubcheck$ pip install Wand
Requirement already satisfied: Wand in [...]

~/aclpubcheck$ python aclpubcheck/formatchecker.py --paper_type long ../[...]
Checking ../[...].pdf

[...]
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

[...]
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
```

Temporary fix: comment out lines 284, 290, 291, 294, 295, 298, 299, 308-312 in formatchecker.py

**Comment by crux82** [comment]
Dear author, 

this is a well-known issue (as discussed here #7 ). I supposed it is due to problems when installing ImageMagick (are you using a MAC?). 

As a workaround, we suggested using an online version of the software, available here: 

https://colab.research.google.com/drive/1Sq6ilmrFUQpUFMkV71U8-Wf0madW-Uer?usp=sharing

Can you check it?
Obviously, it does not solve your issue, but at least it allows you to check your paper. 

Hope this helps
Bests

Danilo

**Comment by jakpra** [comment]
Thanks for the response! Sorry, I should have checked closed issues more thoroughly before posting. It does seem to be the same issue as #7 (both on Windows and Unix for me, as reported by others).

The colab works for me, thanks!

**Comment by kalvinchang** [comment]
what worked for me was
```export MAGICK_HOME=/opt/homebrew/opt/imagemagick@6```

**Comment by ryancotterell** [comment]
Thanks! Would you consider adding this to the documentation?

**Comment by nschneid** [comment]
On my Mac, the uvx command from the README gave the ImageMagick error. The following worked for me (note pip instead of uvx):

    brew install imagemagick
    export MAGICK_HOME=/opt/homebrew/opt/imagemagick
    pip install git+https://github.com/acl-org/aclpubcheck
    aclpubcheck --paper_type long camera-nopages.pdf
